name: amberpencil
description: Amber Pencil
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.4
  flutter_riverpod: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/logo_small.png
    - images/logo_dark.png
    - images/logo_dark_small.png
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.otf
