name: amberpencil
description: Amber pencil
publish_to: 'none'
version: 1.0.1+6
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  firebase_auth: ^3.3.4
  cloud_functions: ^3.2.4
  firebase_storage: ^10.2.4
  universal_html: ^2.0.8
  flutter_markdown: ^0.6.9
  url_launcher: ^6.0.17
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.12
  intl: ^0.17.0
  flutter_native_splash: ^2.0.2
  flex_color_scheme: ^4.2.0
  go_router: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - images/logo.png
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.otf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
# run: $ flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#c0c0c0"
  image: images/logo.png
  color_dark: "#303030"
