name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    env:
      PUB_CACHE: ~/.pub-cache
      NODE_VERSION: '16'
      FLUTTER_VERSION: '2.8.1'

    steps:
      - uses: actions/checkout@v2

      - name: Cache functions/node_modules
        uses: actions/cache@v2
        id: cache-functions-node_modules
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-${{ hashFiles('functions/yarn.lock') }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Flutter packages
        uses: actions/cache@v2
        id: cache-flutter-packages
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-${{ hashFiles('pubspec.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm -g i yarn
      - run: yarn install --frozen-lockfile
      - run: yarn --cwd functions install --frozen-lockfile
      - run: yarn --cwd functions lint
      - run: yarn --cwd functions test

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMBERPENCIL }}'
          projectId: amberpencil
